export const singleEmployedApplicantList = [
  ['applicant', 'single-applicant'],
  ['firstname1', 'test'],
  ['surname1', 'test'],
  ['email1', 'test@test.com'],
  ['phoneNumber1', '11111111'],
  ['mortgageType', 'first-home'],
  ['employed1', 'yes'],
  ['yearly-salary', '22000'],
  ['bonus', '1000'],
  ['other', '0'],
  ['credit-debt', '200'],
  ['loan-debt', '250'],
  ['other-debt', '50'],
];

export const singleUnemployedApplicantList = [
  ['applicant', 'single-applicant'],
  ['firstname1', 'test'],
  ['surname1', 'test'],
  ['email1', 'test@test.com'],
  ['phoneNumber1', '11111111'],
  ['mortgageType', 'first-home'],
  ['employed1', 'no'],
  ['yearly-salary', '12000'],
  ['credit-debt', '200'],
  ['loan-debt', '250'],
  ['other-debt', '50'],
];

export const partnerBothEmployedApplicantList = [
  ['applicant', 'partner-applicant'],
  ['firstname1', 'test'],
  ['surname1', 'test'],
  ['email1', 'test@test.com'],
  ['phoneNumber1', '11111111'],
  ['firstname2', 'test'],
  ['surname2', 'test'],
  ['email2', 'test@test.com'],
  ['phoneNumber2', '11111111'],
  ['mortgageType', 'first-home'],
  ['employed1', 'yes'],
  ['employed2', 'yes'],
  ['yearly-salary', '22000'],
  ['bonus', '1000'],
  ['other', '0'],
  ['yearly-salary', '22000'],
  ['bonus', '1000'],
  ['other', '0'],
  ['credit-debt', '200'],
  ['loan-debt', '250'],
  ['other-debt', '50'],
  ['credit-debt', '200'],
  ['loan-debt', '250'],
  ['other-debt', '50'],
];

export const partnerBothUnemployedApplicantList = [
    ['applicant', 'partner-applicant'],
    ['firstname1', 'test'],
    ['surname1', 'test'],
    ['email1', 'test@test.com'],
    ['phoneNumber1', '11111111'],
    ['firstname2', 'test'],
    ['surname2', 'test'],
    ['email2', 'test@test.com'],
    ['phoneNumber2', '11111111'],
    ['mortgageType', 'first-home'],
    ['employed1', 'no'],
    ['employed2', 'no'],
    ['yearly-salary', '12000'],
    ['yearly-salary', '12000'],
    ['credit-debt', '200'],
    ['loan-debt', '250'],
    ['other-debt', '50'],
    ['credit-debt', '200'],
    ['loan-debt', '250'],
    ['other-debt', '50'],
];

export const partner1EmployedPartner2UnemployedApplicantList = [
    ['applicant', 'partner-applicant'],
    ['firstname1', 'test'],
    ['surname1', 'test'],
    ['email1', 'test@test.com'],
    ['phoneNumber1', '11111111'],
    ['firstname2', 'test'],
    ['surname2', 'test'],
    ['email2', 'test@test.com'],
    ['phoneNumber2', '11111111'],
    ['mortgageType', 'first-home'],
    ['employed1', 'yes'],
    ['employed2', 'no'],
    ['yearly-salary', '22000'],
    ['bonus', '1000'],
    ['other', '0'],
    ['yearly-salary', '12000'],
    ['credit-debt', '200'],
    ['loan-debt', '250'],
    ['other-debt', '50'],
    ['credit-debt', '200'],
    ['loan-debt', '250'],
    ['other-debt', '50'],
];

export const partner1UnemployedPartner2EmployedApplicantList = [
    ['applicant', 'partner-applicant'],
    ['firstname1', 'test'],
    ['surname1', 'test'],
    ['email1', 'test@test.com'],
    ['phoneNumber1', '11111111'],
    ['firstname2', 'test'],
    ['surname2', 'test'],
    ['email2', 'test@test.com'],
    ['phoneNumber2', '11111111'],
    ['mortgageType', 'first-home'],
    ['employed1', 'no'],
    ['employed2', 'yes'],
    ['yearly-salary', '12000'],
    ['yearly-salary', '22000'],
    ['bonus', '1000'],
    ['other', '0'],
    ['credit-debt', '200'],
    ['loan-debt', '250'],
    ['other-debt', '50'],
    ['credit-debt', '200'],
    ['loan-debt', '250'],
    ['other-debt', '50'],
];
